import {
  CanvasNode,
  RelationshipEdge,
  isTableNode,
  isRelationshipEdge,
  TableNode,
  TableRecord,
} from "../types/canvas";

export function generateDBML(
  nodes: CanvasNode[],
  edges: RelationshipEdge[],
): string {
  const tableNodes = nodes.filter(isTableNode);
  const relationshipEdges = edges.filter(isRelationshipEdge);

  let dbml = "";

  // Project Metadata
  dbml += `Project eflow_schema {\n  database_type: 'PostgreSQL'\n  Note: 'Auto-generated by eflow'\n}\n\n`;

  // 1. Tables
  tableNodes.forEach((node) => {
    const { name, columns, indexes, notes } = node.data;

    // Skip tables without a valid name to avoid parser errors
    if (!name || !name.trim()) return;

    dbml += `Table ${name} {\n`;

    // Columns — identifiers must NOT be quoted in DBML
    columns.forEach((col) => {
      // Skip columns with empty names (e.g. during creation)
      if (!col.name || !col.name.trim()) return;

      const colType = col.type || "varchar";
      let line = `  ${col.name} ${colType}`;

      const settings: string[] = [];
      if (col.isPk) settings.push("pk");
      if (col.isUnique && !col.isPk) settings.push("unique");
      if (!col.nullable && !col.isPk) settings.push("not null");
      if (col.isAutoIncrement) settings.push("increment");
      if (
        col.defaultValue !== undefined &&
        col.defaultValue !== null &&
        col.defaultValue !== ""
      ) {
        settings.push(`default: \`${col.defaultValue}\``);
      }
      if (col.notes) settings.push(`note: '${col.notes.replace(/'/g, "\\'")}'`);

      if (settings.length > 0) {
        line += ` [${settings.join(", ")}]`;
      }

      dbml += line + "\n";
    });

    // Indexes
    if (indexes && indexes.length > 0) {
      dbml += "\n  indexes {\n";
      indexes.forEach((idx) => {
        // Filter out empty column names before generating the index
        const validCols = idx.columns.filter((c) => c && c.trim());
        if (validCols.length === 0) return;

        // Single-column: just the identifier. Multi-column: (col1, col2)
        let idxDef: string;
        if (validCols.length === 1) {
          idxDef = validCols[0];
        } else {
          idxDef = `(${validCols.join(", ")})`;
        }

        const idxSettings: string[] = [];
        if (idx.isUnique) idxSettings.push("unique");
        if (idx.type && idx.type !== "btree")
          idxSettings.push(`type: ${idx.type}`);
        if (idx.name) idxSettings.push(`name: '${idx.name}'`);

        if (idxSettings.length > 0) {
          idxDef += ` [${idxSettings.join(", ")}]`;
        }
        dbml += `    ${idxDef}\n`;
      });
      dbml += "  }\n";
    }

    if (notes) {
      dbml += `\n  Note: '${notes.replace(/'/g, "\\'")}'\n`;
    }

    dbml += "}\n\n";
  });

  // 2. Relationships — emit even if no explicit FK column exists
  relationshipEdges.forEach((edge) => {
    const sourceNode = nodes.find((n) => n.id === edge.source) as TableNode;
    const targetNode = nodes.find((n) => n.id === edge.target) as TableNode;

    if (!sourceNode?.data?.name || !targetNode?.data?.name) return;

    const targetPk = targetNode.data.columns.find((c) => c.isPk)?.name ?? "id";

    // First, try to use the column referenced by the edge's sourceHandle (if it exists)
    let fkColumn: string | undefined;

    if (edge.sourceHandle) {
      // Extract column ID from sourceHandle (format: "{columnId}-source")
      // Remove the "-source" or "-target" suffix to get the full column ID
      const sourceColId = edge.sourceHandle
        .replace(/-source$/, "")
        .replace(/-target$/, "");
      const sourceCol = sourceNode.data.columns.find(
        (c) => c.id === sourceColId,
      );
      if (sourceCol) {
        fkColumn = sourceCol.name;
      }
    }

    if (!fkColumn) {
      // Fallback 1: Use any column marked with isFk=true and contains target table name
      fkColumn = sourceNode.data.columns.find(
        (c) =>
          c.isFk &&
          c.name.toLowerCase().includes(targetNode.data.name.toLowerCase()),
      )?.name;
    }

    if (!fkColumn) {
      // Fallback 2: Use any column marked as FK
      fkColumn = sourceNode.data.columns.find((c) => c.isFk)?.name;
    }

    if (!fkColumn) {
      // Fallback 3: Use column that looks like FK (ends with _id, contains target name)
      fkColumn = sourceNode.data.columns.find(
        (c) =>
          c.name.toLowerCase().endsWith("_id") &&
          c.name.toLowerCase().includes(targetNode.data.name.toLowerCase()),
      )?.name;
    }

    if (!fkColumn) {
      // Fallback 4: Use any column ending with _id
      fkColumn = sourceNode.data.columns.find((c) =>
        c.name.toLowerCase().endsWith("_id"),
      )?.name;
    }

    if (!fkColumn) {
      // Fallback 5: Use first non-PK column
      fkColumn = sourceNode.data.columns.find((c) => !c.isPk)?.name;
    }

    // If still no column found, cannot emit Ref
    if (!fkColumn) return;

    // DBML Ref operators:
    // - ">" : many-to-one (source table has many, target has one)
    // - "<" : one-to-many (source table has one, target has many)
    // - "-" : one-to-one
    // - "<>": many-to-many
    //
    // Canvas cardinality "1:n" means: source → target where source=1, target=many
    // So for source.user_id → target.users (1:n), we render: posts.user_id > users
    const card = edge.data?.cardinality;
    let op = ">";
    if (card === "1:1") op = "-";
    else if (card === "1:n")
      op = ">"; // one side → many side = many-to-one from FK perspective
    else if (card === "n:1")
      op = "<"; // many side → one side = one-to-many from FK perspective
    else if (card === "n:m") op = "<>";

    dbml += `Ref: ${sourceNode.data.name}.${fkColumn} ${op} ${targetNode.data.name}.${targetPk}`;

    const refSettings: string[] = [];
    if (edge.data?.onDelete)
      refSettings.push(`delete: ${edge.data.onDelete.toLowerCase()}`);
    if (edge.data?.onUpdate)
      refSettings.push(`update: ${edge.data.onUpdate.toLowerCase()}`);
    if (edge.data?.fkName) refSettings.push(`name: '${edge.data.fkName}'`);

    if (refSettings.length > 0) {
      dbml += ` [${refSettings.join(", ")}]`;
    }

    dbml += "\n";
  });

  // 3. Records (seed data) — roundtrip dbdiagram.io format
  tableNodes.forEach((node) => {
    const { name, columns, records } = node.data;
    if (!name?.trim() || !records || records.length === 0) return;

    const colNames = columns.map((c) => c.name).filter(Boolean);
    dbml += `\nRecords ${name}(${colNames.join(", ")}) {\n`;

    records.forEach((row: TableRecord) => {
      const values = colNames.map((col) => {
        const val = row[col] ?? "";
        // Quote strings that aren't pure numbers
        return /^\d+(\.\d+)?$/.test(val) ? val : `'${val}'`;
      });
      dbml += `  ${values.join(", ")}\n`;
    });

    dbml += "}\n";
  });

  return dbml;
}
