import { CanvasNode, RelationshipEdge, isTableNode, isRelationshipEdge, TableNode, TableRecord } from "../types/canvas";

export function generateDBML(nodes: CanvasNode[], edges: RelationshipEdge[]): string {
    const tableNodes = nodes.filter(isTableNode);
    const relationshipEdges = edges.filter(isRelationshipEdge);

    let dbml = "";

    // Project Metadata
    dbml += `Project eflow_schema {\n  database_type: 'PostgreSQL'\n  Note: 'Auto-generated by eflow'\n}\n\n`;

    // 1. Tables
    tableNodes.forEach((node) => {
        const { name, columns, indexes, notes, records } = node.data;

        // Skip tables without a valid name to avoid parser errors
        if (!name || !name.trim()) return;

        dbml += `Table ${name} {\n`;

        // Columns — identifiers must NOT be quoted in DBML
        columns.forEach((col) => {
            // Skip columns with empty names (e.g. during creation)
            if (!col.name || !col.name.trim()) return;

            const colType = col.type || "varchar";
            let line = `  ${col.name} ${colType}`;

            const settings: string[] = [];
            if (col.isPk) settings.push("pk");
            if (col.isUnique && !col.isPk) settings.push("unique");
            if (!col.nullable && !col.isPk) settings.push("not null");
            if (col.isAutoIncrement) settings.push("increment");
            if (col.defaultValue !== undefined && col.defaultValue !== null && col.defaultValue !== "") {
                settings.push(`default: \`${col.defaultValue}\``);
            }
            if (col.notes) settings.push(`note: '${col.notes.replace(/'/g, "\\'")}'`);

            if (settings.length > 0) {
                line += ` [${settings.join(", ")}]`;
            }

            dbml += line + "\n";
        });

        // Indexes
        if (indexes && indexes.length > 0) {
            dbml += "\n  indexes {\n";
            indexes.forEach((idx) => {
                // Filter out empty column names before generating the index
                const validCols = idx.columns.filter(c => c && c.trim());
                if (validCols.length === 0) return;

                // Single-column: just the identifier. Multi-column: (col1, col2)
                let idxDef: string;
                if (validCols.length === 1) {
                    idxDef = validCols[0];
                } else {
                    idxDef = `(${validCols.join(", ")})`;
                }

                const idxSettings: string[] = [];
                if (idx.isUnique) idxSettings.push("unique");
                if (idx.type && idx.type !== "btree") idxSettings.push(`type: ${idx.type}`);
                if (idx.name) idxSettings.push(`name: '${idx.name}'`);

                if (idxSettings.length > 0) {
                    idxDef += ` [${idxSettings.join(", ")}]`;
                }
                dbml += `    ${idxDef}\n`;
            });
            dbml += "  }\n";
        }

        if (notes) {
            dbml += `\n  Note: '${notes.replace(/'/g, "\\'")}'\n`;
        }

        dbml += "}\n\n";
    });

    // 2. Relationships — only emit when a matching FK column actually exists
    relationshipEdges.forEach((edge) => {
        const sourceNode = nodes.find(n => n.id === edge.source) as TableNode;
        const targetNode = nodes.find(n => n.id === edge.target) as TableNode;

        if (!sourceNode?.data?.name || !targetNode?.data?.name) return;

        const targetPk = targetNode.data.columns.find(c => c.isPk)?.name ?? "id";

        // Only use an FK column that ACTUALLY EXISTS in the source table
        const fkColumn = sourceNode.data.columns.find(
            c => c.isFk && c.name.toLowerCase().includes(targetNode.data.name.toLowerCase())
        )?.name;

        // If no explicit FK column found, skip the Ref to avoid parser errors
        // (the edge stays in the canvas; it just won't appear in DBML)
        if (!fkColumn) return;

        // DBML Ref: > = many-to-one, < = one-to-many, - = one-to-one, <> = many-to-many
        const card = edge.data?.cardinality;
        let op = ">";
        if (card === "1:1") op = "-";
        else if (card === "1:n") op = "<";
        else if (card === "n:m") op = "<>";

        dbml += `Ref: ${sourceNode.data.name}.${fkColumn} ${op} ${targetNode.data.name}.${targetPk}`;

        const refSettings: string[] = [];
        if (edge.data?.onDelete) refSettings.push(`delete: ${edge.data.onDelete.toLowerCase()}`);
        if (edge.data?.onUpdate) refSettings.push(`update: ${edge.data.onUpdate.toLowerCase()}`);
        if (edge.data?.fkName) refSettings.push(`name: '${edge.data.fkName}'`);

        if (refSettings.length > 0) {
            dbml += ` [${refSettings.join(", ")}]`;
        }

        dbml += "\n";
    });

    // 3. Records (seed data) — roundtrip dbdiagram.io format
    tableNodes.forEach((node) => {
        const { name, columns, records } = node.data;
        if (!name?.trim() || !records || records.length === 0) return;

        const colNames = columns.map(c => c.name).filter(Boolean);
        dbml += `\nRecords ${name}(${colNames.join(", ")}) {\n`;

        records.forEach((row: TableRecord) => {
            const values = colNames.map(col => {
                const val = row[col] ?? "";
                // Quote strings that aren't pure numbers
                return /^\d+(\.\d+)?$/.test(val) ? val : `'${val}'`;
            });
            dbml += `  ${values.join(", ")}\n`;
        });

        dbml += "}\n";
    });

    return dbml;
}
